---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1

Follow the instructions posted at <https://ds202-at-isu.github.io/labs.html> for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.

All submissions to the github repo will be automatically uploaded for grading once the due date is passed. Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.

-------------------------------------------------------------------------------------------------------
This is a line from RStudio!

This is a line from RStudio (Hong Hao Khoo)

-------------------------------------------- Lab 1 Report ---------------------------------------------

Chapter 12.1

-   Analyn: Prerequisites were complete before class. Introduced myself to the group.
-   Brandon: Double checked I had introduced myself. I had.
-   Jenna: This is a test.
-   Hong Hao: Completed this before class. Introduced myself to the group through outlook. 

Chapter 12.2

-   Analyn: The repo was already created as part of the assignment.
-   Brandon: Used the repo we already had. Hurray!
-   Jenna: Already had a repo!
-   Hong Hao: I created the repo and named it "Team 4 Lab 1"

Chapter 12.3

-   Analyn: I cloned the GitHub to my class folder, it worked perfectly.
-   Brandon: Cloned it!
-   Jenna: Successfully cloned the project!
-   Hong Hao: Followed the steps in chapter 12.3 and cloned it successfully using the HTTPS URL.

Chapter 12.4

-   Analyn: I added the line "This is a line from RStudio" in RStudio. I then staged and commited the README.Rmd file.
-   Brandon: Hey look this step is what I'm doing now :)
-   Jenna:
-   Hong Hao: I added the line "This is a line from RStudio (Hong Hao Khoo)". I staged it, committed the README.Rmd file. 

Chapter 12.5

-   Analyn: I pushed it using the push button.
-   Brandon: First commit didn't work lets try again
-   Jenna:
-   Hong Hao: I pushed the file and it worked.

Chapter 12.6

-   Analyn: I double checked everything worked on the GitHub repo. Once I confirmed it worked, I repeated steps 4 - 6 to add these comments. I also fixed formatting errors.
-   Brandon: Big formatting errors they did not combine correctly so fixing it now
-   Jenna:
-   Hong Hao: After pushing the line "This is a line from RStudio" and it works, I added my comments for each step and push it as well.

